### ISSUE TITLE
Advanced craftingtable Bug

### ISSUE THREAD

**Issue by MaucnAD** [Leviathan143/betterbeginnings-MODIFIED#30] opened 2017-03-08 13:48 UTC
Whenever I have more than one of the ingredients of a crafting recipe in the table, it uses all the ingredients but I only get one of the item I want to craft instead of the number of the recipe I have in there

Steps to reproduce:
Craft an item
Try to make more than one of the item
Result: Get one of the item you want to craft, consumes all of the items regardless

Version Info(Exact versions only):
BetterBeginnings: b0.9.8-R4c

Forge: 12.18.3.2239

Minecraft: 1.10.2

No crash, game itself is fine

**Comment by Leviathan143** [comment] 2017-03-08 18:08
This is a duplicate of #29. Please search for existing issues before creating a new one.

**Closed by Leviathan143** 2017-03-08 18:08 UTC
Labels: 1.10.2, duplicate
