### ISSUE TITLE
Removing Kiln recipes with CraftTweaker still show in JEI

### ISSUE THREAD

**Issue by davqvist** [Leviathan143/betterbeginnings-MODIFIED#60] opened 2017-06-10 11:01 UTC
Please fill out **all** applicable sections in the template below:

**Description:**
When I remove a Kiln recipe with mods.betterbeginnings.Kiln.removeOutput, it works, but the recipe still shows in JEI. Also every time you do /mt reload the recipe even shows an additional time.

**Steps to reproduce:**
Add a CraftTweaker script with the following line
`mods.betterbeginnings.Kiln.removeOutput(<minecraft:coal:1>);`
Start the instance
Check JEI for the Kiln uses or Charcoal recipes.

**Version Info(Exact versions only):**
BetterBeginnings: b0.9.8-R6d
Forge: 2297
Minecraft: 1.10.2

**Logs and other useful information:**
I haven't tested yet, but maybe you could test the other blocks as well, maybe they are affected by the same bug.

**Comment by Leviathan143** [comment] 2017-06-10 20:09
Duplicate of #53. Already fixed in dev

**Closed by Leviathan143** 2017-06-10 20:09 UTC
Labels: 1.10.2, duplicate

**Comment by davqvist** [comment] 2017-06-10 20:25
Sorry, didn't see, thanks
