### ISSUE TITLE
Small question about the config settings

### ISSUE THREAD

**Issue by g-ooden** [Leviathan143/betterbeginnings-MODIFIED#48] opened 2017-05-25 02:25 UTC
Sorry for needing to ask here about such a small query, but how do I go about using the tweaks section of the config? I wish to add a tool to the list of "Also axes" but I can't seem to figure out how to input it. Could someone show me an example?
I've tried excompressum:compressed_hammer_stone, excompressum:compressed_hammer_stone=stone, and excompressum:compressed_hammer=stone.
![tweaks](https://cloud.githubusercontent.com/assets/28941038/26433297/b54c1874-40b6-11e7-9fd7-9918bc92149a.PNG)

BetterBeginnings: MC1.10.2-b0.9.8-R6c

Forge: 1.10.2-12.18.3.2297

Minecraft: 1.10.2

**Comment by Leviathan143** [comment] 2017-05-25 02:48
Tool tier is an integer from 0 to 4. Each integer corresponds to a mining level from wood to diamond.

**Comment by g-ooden** [comment] 2017-05-25 02:56
![bbings](https://cloud.githubusercontent.com/assets/28941038/26434012/000e1c96-40bb-11e7-87a8-46b0c4381c24.PNG)
![configfile](https://cloud.githubusercontent.com/assets/28941038/26434011/0009a472-40bb-11e7-9ed6-193095b0914a.PNG)
![excompress](https://cloud.githubusercontent.com/assets/28941038/26434013/000ff494-40bb-11e7-91dd-0e33d4438513.PNG)

**Comment by Leviathan143** [comment] 2017-06-08 23:25
A fix for this is in the works. It's delayed due to unexpected behaviour.

**Closed** 2017-06-10 21:42 UTC
Labels: 1.10.2, bug
