### ISSUE TITLE
Delay when move an item

### ISSUE THREAD

**Issue by wenlfs** [Leviathan143/betterbeginnings-MODIFIED#65] opened 2017-06-24 06:45 UTC
Please fill out **all** applicable sections in the template below:

**Description:**
 
I noticed some delay when I moved an item in a slot to another, it happened on campfire GUI and maybe happen in others (I didn't have enough time to test everything)

**Steps to reproduce:**

Try move an item in a slot to another in campfire GUI.

**Version Info(Exact versions only):**
BetterBeginnings:  0.9.8 R6d

Forge: 12.18.3.2185

Minecraft: 1.10.2

**Logs and other useful information:**

**Comment by Leviathan143** [comment] 2017-06-24 09:36
This sounds like some kind of lag to me. I couldn't reproduce it either. Could you make a video or GIF of the issue? Does it happen with GUIs from other mods?

**Comment by wenlfs** [comment] 2017-06-24 18:30
I'm in doubt if it's lag, because I moved the item and it was displayed in the slot and in the pointer at same time. I'll do more tests and check other mods, but I can provide a video or GIF now, So I'll provide some proof when I can if it really continue. Sorry and thanks.

**Comment by Leviathan143** [comment] 2017-07-15 01:45
@wenlfs Any more info on this? 
If I don't get more info within 7 days of posting this comment, I will close this issue. This is standard procedure for issues that cannot be reproduced.

**Comment by Leviathan143** [comment] 2017-07-25 05:13
Closing as per previous comment

**Closed by Leviathan143** 2017-07-25 05:13 UTC
Labels: 1.10.2, Could not reproduce
